---
- user: name={{ user }} comment="LXC guest"
- file: path=~{{ user }}/.config/lxc state=directory owner={{ user }} group={{ user }}
- shell: "grep {{ user }} /etc/subuid |cut -d: -f2"
  register: subuid
  changed_when: False
  always_run: True
- shell: "grep {{ user }} /etc/subgid |cut -d: -f2"
  register: subgid
  changed_when: False
  always_run: True
- set_fact: subuid={{ subuid.stdout }} subgid={{ subgid.stdout }}
- template: src=default.conf.j2 dest=~{{ user }}/.config/lxc/default.conf owner={{ user }} group={{ user }}
- command: cgm create all {{ user }}
- shell: cgm chown all {{ user }}  $(id -u {{ user }}) $(id -g {{ user }})
- shell: "cgm movepid all {{ user }} $$; lxc-create -t download -n {{ user }} -- -d ubuntu -r trusty -a amd64"
  sudo: yes
  sudo_user: "{{ user }}"
  args:
    creates: ~{{ user }}/.local/share/lxc/{{ user }}/config
- copy: src=start-lxc.sh dest=~{{ user}}/start-lxc.sh owner={{ user }} group={{ user }} mode=0755
- cron: name="start lxc" special_time=reboot job="$HOME/start-lxc.sh" user={{ user }}
- command: lxc-ls --running
  sudo: yes
  sudo_user: "{{ user }}"
  changed_when: False
  always_run: True
  register: lxcls
- command: "~{{ user }}/start-lxc.sh"
  sudo: yes
  sudo_user: "{{ user }}"
  when: user not in lxcls.stdout_lines
