---
- apt: name={{item}} state=latest
  with_items:
  - lxc
  - bridge-utils
  - libvirt-bin
  - debootstrap
  - cgmanager
  - uidmap
- sysctl: name=kernel.unprivileged_userns_clone value=1
- sysctl: name=net.ipv4.ip_forward value=1
  when: networking
