---
- apt: name={{item}} state=latest
  with_items:
  - lxc
  - bridge-utils
  - libvirt-bin
  - debootstrap
  - cgmanager
  - uidmap
- service: name=cgmanager state=started enabled=yes
- sysctl: name=kernel.unprivileged_userns_clone value=1
- sysctl: name=net.ipv4.ip_forward value=1
  when: networking
- copy: src=bridge dest=/etc/network/interfaces.d/lxc-bridge
  when: networking
  register: bridge
- command: ifup lxc-bridge-nat
  when: bridge|changed
